name: CS2 Schema Radar Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Kodu Depodan Cek
      uses: actions/checkout@v4

    - name: MSBuild ve Visual Studio Araclarini Yukle
      uses: microsoft/setup-msbuild@v2

    - name: CMake Yapilandirmasini Olustur
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Projeyi C++20 Modunda Derle
      run: cmake --build build --config Release

    - name: Olusan EXE Dosyasini Artifact Olarak Yukle
      uses: actions/upload-artifact@v4
      with:
        name: CS2-Schema-Radar
        path: build/Release/*.exe
        
